name: Publish Package to npmjs
on:
  workflow_dispatch
  
jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: step-security/wait-for-secrets@v1
        id: get-otp
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          secrets: |
            otp
            secret1
      - run: | 
          echo ${{ steps.get-otp.outputs.otp }}
          echo ${{ steps.get-otp.outputs.secret1 }}
        
