name: Lint
on:
  pull_request:
    branches: main
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo resolvectl flush-caches
      - name: Harden Runner
        uses: step-security/harden-runner@v1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - run: npx semver v1.9.8
      
